//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULDCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULDCustomer
    {
        public int ULDCustomerID { get; set; }
        public Nullable<int> ULDSurveyID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> productIDPurchased { get; set; }
        public Nullable<System.DateTime> datePurchased { get; set; }
        public Nullable<System.DateTime> dateValidated { get; set; }
        public Nullable<byte> ValidatedFlag { get; set; }
    }
}
