//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULDCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULDSurveyAnswer
    {
        public int ULDSurveyAnswerID { get; set; }
        public Nullable<int> ULDQuestionID { get; set; }
        public Nullable<int> ULDSurveyID { get; set; }
        public string answer { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
